import os
import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv
from groq import Groq, GroqError
from pypdf import PdfReader

logger = logging.getLogger(__name__)

PRIMARY_MODEL = "openai/gpt-oss-120b"
FALLBACK_MODELS = [
    "openai/gpt-oss-20b",
    "groq/compound",
    "groq/compound-mini",
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant",
]


def get_groq_client() -> Optional[Groq]:
    env_file = Path(__file__).resolve().parent.parent / '.env'
    load_dotenv(env_file, override=True)
    api_key = os.getenv("GROQ_API_KEY")

    if not api_key or api_key.strip() == "" or "your_groq_api_key" in api_key:
        logger.warning("GROQ_API_KEY is unconfigured or invalid.")
        return None
    return Groq(api_key=api_key.strip())


def extract_text_from_pdf(file_path: str) -> str:
    text = ""
    try:
        reader = PdfReader(file_path)
        for page in reader.pages:
            extracted = page.extract_text()
            if extracted:
                text += extracted + "\n"
    except Exception as exc:
        logger.error(f"Error extracting text from PDF ({file_path}): {exc}")
        text = f"[Extraction failed: {exc}]"
    return text.strip()


def call_groq_json(system_prompt: str, user_prompt: str) -> Dict[str, Any]:
    client = get_groq_client()
    if not client:
        return {
            "error": "GROQ_API_KEY is not configured.",
            "category": "General",
            "document_type": "Unclassified",
            "summary": "Service unavailable due to missing API credentials.",
            "metadata_fields": {},
            "missing_fields": [],
        }

    models = [PRIMARY_MODEL] + FALLBACK_MODELS
    last_error = ""

    for model in models:
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                response_format={"type": "json_object"},
                temperature=0.1,
                max_tokens=4096,
            )
            content = response.choices[0].message.content
            return json.loads(content)
        except GroqError as ge:
            last_error = str(ge)
            logger.warning(f"Groq API error on model {model}: {ge}")
        except json.JSONDecodeError as je:
            last_error = str(je)
            logger.error(f"JSON decode failure on model {model}: {je}")
            return {"error": "Invalid JSON response generated by model."}
        except Exception as exc:
            last_error = str(exc)
            logger.error(f"Unexpected error on model {model}: {exc}")

    return {"error": f"Groq execution failed across available models. Details: {last_error}"}


def classify_and_enrich_document(document_text: str) -> Dict[str, Any]:
    """Perform semantic classification, extract metadata fields, and detect missing values."""
    truncated_text = document_text[:28000]

    system_prompt = (
        "You are an intelligent Enterprise Document Semantic Classifier & Metadata Analyzer. "
        "Analyze the provided document content and produce a structured analysis in STRICT JSON format.\n"
        "Your JSON MUST strictly adhere to the following keys:\n"
        "{\n"
        '  "category": "Semantic category (e.g., Human Resources, Legal & Contracts, Standard Operating Procedures (SOP), Financials & Accounting, Production & Operations, Customer Policy)",\n'
        '  "document_type": "Specific document title/type (e.g., Quality SOP, Expense Policy, Non-Disclosure Agreement, Invoice)",\n'
        '  "summary": "Concise executive summary of what this document covers (string)",\n'
        '  "metadata_fields": {\n'
        '    "title": "Document Title",\n'
        '    "department": "Department or Author",\n'
        '    "effective_date": "Effective Date or Date",\n'
        '    "key_scope": "Scope or Subject Matter"\n'
        '  },\n'
        '  "missing_fields": ["Array of missing metadata values, missing clauses, or missing required fields in this document"]\n'
        "}"
    )

    user_prompt = f"Perform semantic analysis on the following document content:\n\n{truncated_text}"
    return call_groq_json(system_prompt, user_prompt)


def ask_company_knowledge_base(question: str, indexed_docs_data: List[Dict[str, str]]) -> Dict[str, Any]:
    """
    General purpose personalized company chatbot Q&A.
    Queries across all company documents in data directory.
    """
    if not indexed_docs_data:
        return {
            "question": question,
            "answer": "No indexed company documents found in the database. Please upload company documents in the 'Document Ingestion' tab first.",
            "sources": []
        }

    # Combine text from indexed documents
    context_str = ""
    for doc in indexed_docs_data[:10]:  # Up to 10 docs
        context_str += f"=== DOCUMENT: {doc['title']} (Category: {doc.get('category', 'General')}) ===\n"
        context_str += doc['text'][:8000] + "\n\n"

    system_prompt = (
        "You are the official Personalized AI Assistant for the company. "
        "Your task is to answer employee questions strictly and accurately based on the company data and documents provided in context. "
        "If the answer is found in the documents, provide a helpful, clear, professional response and cite the exact document name. "
        "If the information is not present in the documents, state politely: 'This information is not currently found in the company's indexed documents.' "
        "Provide your output strictly in JSON format with structure:\n"
        "{\n"
        '  "question": "The employee question (string)",\n'
        '  "answer": "Comprehensive personalized response (string)",\n'
        '  "sources": [\n'
        '    {\n'
        '      "document_title": "Name of source document",\n'
        '      "excerpt": "Relevant quote or excerpt from the document supporting the answer"\n'
        '    }\n'
        '  ]\n'
        "}"
    )

    user_prompt = f"Company Documents Context:\n{context_str}\n\nEmployee Question: {question}"
    result = call_groq_json(system_prompt, user_prompt)

    if isinstance(result, dict) and "question" not in result:
        result["question"] = question
    return result

def ask_document(document_text: str, question: str) -> Dict[str, Any]:
    """
    Ask a specific question against a single document's text.
    """
    truncated_text = document_text[:28000]

    system_prompt = (
        "You are an intelligent Document Q&A Assistant. "
        "Your task is to answer user questions accurately based ONLY on the provided document text. "
        "If the answer is found in the text, provide a helpful, clear, professional response. "
        "If the information is not present, state politely: 'This information is not found in the document.' "
        "Provide your output strictly in JSON format with structure:\n"
        "{\n"
        '  "question": "The question asked (string)",\n'
        '  "answer": "Comprehensive personalized response (string)",\n'
        '  "sources": [\n'
        '    {\n'
        '      "excerpt": "Relevant quote or excerpt from the document supporting the answer"\n'
        '    }\n'
        '  ],\n'
        '  "confidence": "Confidence score (e.g. 95%)"\n'
        "}"
    )

    user_prompt = f"Document Context:\n{truncated_text}\n\nQuestion: {question}"
    result = call_groq_json(system_prompt, user_prompt)

    if isinstance(result, dict) and "question" not in result:
        result["question"] = question
    return result

def compare_documents(doc1_text: str, doc2_text: str) -> Dict[str, Any]:
    """
    Compare two documents and highlight the differences, added clauses, removed clauses, etc.
    """
    t1 = doc1_text[:14000]
    t2 = doc2_text[:14000]

    system_prompt = (
        "You are an expert Legal and Document Analyst. "
        "Compare Version 1 and Version 2 of the document provided. "
        "Identify material modifications, removed clauses, and new obligations. "
        "Provide your output strictly in JSON format with structure:\n"
        "{\n"
        '  "risk_impact": "Integer (e.g. 48)",\n'
        '  "summary": "Brief summary of differences",\n'
        '  "differences": [\n'
        '    {\n'
        '      "section": "Clause or Section name",\n'
        '      "v1_text": "Original text summary",\n'
        '      "v2_text": "Revised text summary",\n'
        '      "significance": "CRITICAL, MODERATE, or MINOR",\n'
        '      "status": "Changed, Added, or Removed"\n'
        '    }\n'
        '  ]\n'
        "}"
    )

    user_prompt = f"Version 1 (Original):\n{t1}\n\nVersion 2 (Revised):\n{t2}\n\nCompare the documents."
    result = call_groq_json(system_prompt, user_prompt)
    
    return result

