import json
import logging
import os
from pathlib import Path
from typing import Any, Dict, Optional

from dotenv import load_dotenv
from groq import Groq, GroqError
from pypdf import PdfReader

logger = logging.getLogger(__name__)

PRIMARY_MODEL = "openai/gpt-oss-120b"
FALLBACK_MODELS = [
    "openai/gpt-oss-20b",
    "groq/compound",
    "groq/compound-mini",
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant",
]


def get_groq_client() -> Optional[Groq]:
    env_file = Path(__file__).resolve().parent.parent / '.env'
    load_dotenv(env_file, override=True)
    api_key = os.getenv("GROQ_API_KEY")

    if not api_key or api_key.strip() == "" or "your_groq_api_key" in api_key:
        logger.warning("GROQ_API_KEY is unconfigured or invalid.")
        return None
    return Groq(api_key=api_key.strip())


def extract_text_from_pdf(file_path: str) -> str:
    text = ""
    try:
        reader = PdfReader(file_path)
        for page in reader.pages:
            extracted = page.extract_text()
            if extracted:
                text += extracted + "\n"
    except Exception as exc:
        logger.error(f"Error extracting text from PDF ({file_path}): {exc}")
        text = f"[Extraction failed: {exc}]"
    return text.strip()


def call_groq_json(system_prompt: str, user_prompt: str) -> Dict[str, Any]:
    client = get_groq_client()
    if not client:
        return {
            "error": "GROQ_API_KEY is not configured.",
            "summary": "Service unavailable due to missing API credentials.",
            "document_type": "Unknown",
            "key_information": {},
            "missing_clauses": [],
            "compliance_risks": [],
            "overall_risk_level": "LOW",
        }

    models = [PRIMARY_MODEL] + FALLBACK_MODELS
    last_error = ""

    for model in models:
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                response_format={"type": "json_object"},
                temperature=0.1,
                max_tokens=4096,
            )
            content = response.choices[0].message.content
            return json.loads(content)
        except GroqError as ge:
            last_error = str(ge)
            logger.warning(f"Groq API error on model {model}: {ge}")
        except json.JSONDecodeError as je:
            last_error = str(je)
            logger.error(f"JSON decode failure on model {model}: {je}")
            return {"error": "Invalid JSON response generated by model."}
        except Exception as exc:
            last_error = str(exc)
            logger.error(f"Unexpected error on model {model}: {exc}")

    return {"error": f"Groq execution failed across available models. Details: {last_error}"}


def analyze_document_with_groq(document_text: str) -> Dict[str, Any]:
    truncated_text = document_text[:28000]

    system_prompt = (
        "You are an expert legal and compliance AI document analyst. "
        "Analyze the provided document text and produce a comprehensive audit in STRICT JSON format.\n"
        "Your JSON MUST strictly adhere to the following structure:\n"
        "{\n"
        '  "summary": "Detailed overall summary of the document (string)",\n'
        '  "document_type": "Identified document type (e.g., NDA, Vendor Agreement, Service Contract, Employment Contract, Invoice, Policy)",\n'
        '  "key_information": {\n'
        '    "parties": ["Party 1", "Party 2"],\n'
        '    "contract_value": "Monetary terms or contract value",\n'
        '    "effective_date": "Effective date",\n'
        '    "expiration_date": "Expiration or termination date",\n'
        '    "payment_terms": "Payment terms"\n'
        '  },\n'
        '  "missing_clauses": ["Array of critical missing standard legal/compliance clauses"],\n'
        '  "compliance_risks": [\n'
        '    {\n'
        '      "risk": "Short title of risk",\n'
        '      "severity": "HIGH" | "MEDIUM" | "LOW",\n'
        '      "description": "Detailed explanation of risk and potential impact"\n'
        '    }\n'
        '  ],\n'
        '  "overall_risk_level": "HIGH" | "MEDIUM" | "LOW"\n'
        "}"
    )

    user_prompt = f"Analyze the following document content:\n\n{truncated_text}"
    return call_groq_json(system_prompt, user_prompt)


def ask_document_with_groq(document_text: str, question: str) -> Dict[str, Any]:
    truncated_text = document_text[:28000]

    system_prompt = (
        "You are an AI assistant answering questions about a document. "
        "Answer the user's question STRICTLY using only the provided document text. "
        "If the information is not present in the document, explicitly state 'Not found in the document'. "
        "Provide your output strictly in JSON format with structure:\n"
        "{\n"
        '  "question": "The input question (string)",\n'
        '  "answer": "Grounded answer derived ONLY from the document (string)",\n'
        '  "source_snippet": "Exact quote or excerpt supporting the answer (string)"\n'
        "}"
    )

    user_prompt = f"Document Content:\n{truncated_text}\n\nUser Question: {question}"
    result = call_groq_json(system_prompt, user_prompt)
    if isinstance(result, dict) and "question" not in result:
        result["question"] = question
    return result


def compare_documents_with_groq(document_text1: str, document_text2: str) -> Dict[str, Any]:
    doc1_trunc = document_text1[:14000]
    doc2_trunc = document_text2[:14000]

    system_prompt = (
        "You are an expert legal document comparator. "
        "Compare Document Version 1 and Document Version 2. "
        "Identify key changes, clause differences, missing additions, and assess risk impact. "
        "Provide your response STRICTLY in JSON format with structure:\n"
        "{\n"
        '  "summary_of_changes": "High-level summary of changes between Version 1 and Version 2",\n'
        '  "differences": [\n'
        '    {\n'
        '      "field": "Clause or Section Name",\n'
        '      "version_1": "Content/provision in Version 1",\n'
        '      "version_2": "Content/provision in Version 2",\n'
        '      "significance": "HIGH" | "MEDIUM" | "LOW"\n'
        '    }\n'
        '  ],\n'
        '  "risk_assessment": "Detailed explanation of risk differences and overall comparison"\n'
        "}"
    )

    user_prompt = f"=== DOCUMENT VERSION 1 ===\n{doc1_trunc}\n\n=== DOCUMENT VERSION 2 ===\n{doc2_trunc}"
    return call_groq_json(system_prompt, user_prompt)

