# Generated by Django 6.0.6 on 2026-09-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text', models.TextField(blank=True)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('overall_risk', models.CharField(blank=True, default='LOW', max_length=20)),
                ('document_type', models.CharField(blank=True, default='Unknown', max_length=100)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
